apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-app
  template:
    metadata:
      labels:
        app: workflow-app
    spec:
      containers:
      - name: workflow-app
        image: joypatel2403/practise:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASS
        - name: MONGO_URI
          value: "mongodb://$(DB_USER):$(DB_PASS)@mongo:27017/feedback_db?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-app-service
spec:
  type: NodePort
  selector:
    app: workflow-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050